FROM python

WORKDIR /app

RUN pip install nltk && \
    python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"

COPY . /app/
COPY paragraphs.txt /app

CMD [ "python3", "app.py" ]